name: Release
on:
  push:
    tags:
      - '*'

permissions:
  contents: read
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install Helm
        uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v4.3.0
      - name: Install Cosign
        uses: sigstore/cosign-installer@3454372f43399081ed03b604cb2d021dabca52bb # v3.8.2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Package chart
        run: |
          helm package charts/vaultwarden
      - name: Push chart
        run: |
          helm push vaultwarden-*.tgz oci://ghcr.io/${{ github.repository }}
      # - name: Sign artifacts with Cosign
      #   run: |
      #     cosign sign --yes ghcr.io/${{ github.repository }}/vaultwarden:${{ github.ref_name }}
